Appitem.create(name:'Google', description:'Search Engine', color:'Red', default_status: 'Yes', link:'http://www.google.com', position:1)
Appitem.create(name:'Wisc', description:'UW Homepage', color:'Blue', default_status: 'No', link:'http://www.wisc.edu', position:2)
Appitem.create(name:'GLBRC', description:'Great Lakes Bioenergy Research Center', color:'Yellow', default_status: 'Yes', link:'http://www.glbrc.org', position:3)
Appitem.create(name:'WEI', description:'Wisconsin Energy Institute', color:'Green', default_status: 'No', link:'https://energy.wisc.edu/', position:4)
Appitem.create(name:'Twitter', description:'Twitter', color:'Purple', default_status: 'No', link:'https://twitter.com/', position:5)